# CMake generated Testfile for 
# Source directory: /home/shreyas/catkin_ws/src/geometric_shapes/test
# Build directory: /home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/geometric_shapes/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_geometric_shapes_gtest_test_basics "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_basics.xml" "--return-code" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/devel/lib/geometric_shapes/test_basics --gtest_output=xml:/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_basics.xml")
add_test(_ctest_geometric_shapes_gtest_test_point_inclusion "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_point_inclusion.xml" "--return-code" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/devel/lib/geometric_shapes/test_point_inclusion --gtest_output=xml:/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_point_inclusion.xml")
add_test(_ctest_geometric_shapes_gtest_test_bounding_sphere "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_bounding_sphere.xml" "--return-code" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/devel/lib/geometric_shapes/test_bounding_sphere --gtest_output=xml:/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_bounding_sphere.xml")
add_test(_ctest_geometric_shapes_gtest_test_bounding_box "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_bounding_box.xml" "--return-code" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/devel/lib/geometric_shapes/test_bounding_box --gtest_output=xml:/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_bounding_box.xml")
add_test(_ctest_geometric_shapes_gtest_test_bounding_cylinder "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_bounding_cylinder.xml" "--return-code" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/devel/lib/geometric_shapes/test_bounding_cylinder --gtest_output=xml:/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_bounding_cylinder.xml")
add_test(_ctest_geometric_shapes_gtest_test_create_mesh "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_create_mesh.xml" "--return-code" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/devel/lib/geometric_shapes/test_create_mesh --gtest_output=xml:/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_create_mesh.xml")
add_test(_ctest_geometric_shapes_gtest_test_loaded_meshes "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_loaded_meshes.xml" "--return-code" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/devel/lib/geometric_shapes/test_loaded_meshes --gtest_output=xml:/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_loaded_meshes.xml")
add_test(_ctest_geometric_shapes_gtest_test_shapes "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_shapes.xml" "--return-code" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/devel/lib/geometric_shapes/test_shapes --gtest_output=xml:/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_shapes.xml")
add_test(_ctest_geometric_shapes_gtest_test_ray_intersection "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_ray_intersection.xml" "--return-code" "/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/devel/lib/geometric_shapes/test_ray_intersection --gtest_output=xml:/home/shreyas/catkin_ws/src/gazebo_plugin_tutorial/test_results/geometric_shapes/gtest-test_ray_intersection.xml")
