set(_CATKIN_CURRENT_PACKAGE "tt_robot")
set(tt_robot_VERSION "0.0.0")
set(tt_robot_MAINTAINER "shreyas <shreyas@todo.todo>")
set(tt_robot_PACKAGE_FORMAT "2")
set(tt_robot_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(tt_robot_BUILD_EXPORT_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz" "xacro" "roscpp" "rospy" "std_msgs")
set(tt_robot_BUILDTOOL_DEPENDS "catkin")
set(tt_robot_BUILDTOOL_EXPORT_DEPENDS )
set(tt_robot_EXEC_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz" "xacro" "roscpp" "rospy" "std_msgs")
set(tt_robot_RUN_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz" "xacro" "roscpp" "rospy" "std_msgs")
set(tt_robot_TEST_DEPENDS "roslaunch")
set(tt_robot_DOC_DEPENDS )
set(tt_robot_URL_WEBSITE "")
set(tt_robot_URL_BUGTRACKER "")
set(tt_robot_URL_REPOSITORY "")
set(tt_robot_DEPRECATED "")